#+options: html-postamble:nil

* Building

** Windows

Building for Windows via MinGW on Linux requires libusb static library and
header to be present under =libusb/= in the source tree. Given the libusb 1.0.19
Windows binary distribution (libusb-1.0.19.7z), which looks like this...

: include/libusb-1.0/libusb.h
: MinGW32/dll/libusb-1.0.dll
: MinGW32/dll/libusb-1.0.dll.a
: [other things we don't care about]

...the =libusb/= directory here must look like this:

: libusb.h
: libusb-1.0.dll
: libusb-1.0.dll.a

** Darwin

libantumbra can be linked against either the system libusb (such as might be
installed with MacPorts, Homebrew, etc) or a custom copy. Only the latter
approach is supported as it is the most portable.

*** Including libusb

Place libusb dynamic library and headers in =libusb/= (this example uses a
default Homebrew install):

: $ mkdir libusb
: $ cp /usr/local/lib/libusb-1.0.0.dylib libusb/libusb.dylib
: $ cp /usr/local/include/libusb-1.0/libusb.h libusb/libusb.h

Dynamic linking is unusual on Darwin in that the target library specifies its
own path ("install name"), which is then stored at build time in the binary that
uses it. Some voodoo must be done in order for runtime library resolution to
work properly. See the Makefile if you're interested.

*** libantumbra.framework

Darwin has the concept of "frameworks". A framework bundles library headers and
binaries together into a single convenient unit. These may be linked against by
passing =-framework SomeFrameworkName= to =ld(1)= or adding them to an Xcode
project.

The basic structure of a framework, named =SomeFrameworkName= in this example,
is thus:

: SomeFrameworkName.framework/  # (appears as a single file in Finder)
:   SomeFrameworkName           # dynamic library without .dylib extension
:   Headers/
:     ...
:   Resources/
:     Info.plist

Most frameworks are more complicated and may include multiple versions or
additional resources. But this is all we need for libantumbra.

On Darwin, =libantumbra.framework= is implied by the =all= target. libusb is
included in the framework.

=libantumbra.framework= assumes it's embedded in your application in the usual
=Frameworks/= bundle subdir. If it isn't, you must change either the install
name of =libantumbra.framework/libantumbra= or your binary's dependency
reference.
